[package]
name = "game_of_life"
version = "0.1.0"
authors = ["vcser <vcser2018@udec.cl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
#rustbox = "0.11.0"